name: qr_attendance
description: "QTick - Smart QR Attendance Tracking"
publish_to: "none"

version: 3.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # QR Code scanning and generation
  mobile_scanner: ^5.0.0
  qr_flutter: ^4.1.0

  # Database
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # State management and utilities
  provider: ^6.1.2
  shared_preferences: ^2.2.3

  # UI and animations
  flutter_staggered_animations: ^1.1.1
  lottie: ^3.1.3

  # Audio
  audioplayers: ^6.1.0

  # Date and time handling
  intl: ^0.19.0

  # Permissions (for camera access)
  permission_handler: ^11.3.1

  # Battery information
  battery_plus: ^6.2.3

  # Google Fonts for playful typography
  google_fonts: ^6.2.1

  # Package for fetching app version info
  package_info_plus: ^4.2.0

  # File operations and CSV export
  path_provider: ^2.1.0
  csv: ^6.0.0
  share_plus: ^10.0.2
  file_picker: ^8.1.2

  # WhatsApp Business API and HTTP requests
  http: ^1.2.2

  # App update functionality
  in_app_update: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
    - assets/sounds/
